---
title: "Propuesta Técnico-Económica"
author: 'autores:'
date: "2022-12-08"
output: pdf_document
---

# Antecedentes generales

**Origen de la solicitud**

La solicitud surge desde el administrador de los "Predios Centro Experimental Forestal" de la
Universidad Austral de Chile, con el fin solicitar los siguientes servicios:

* Realizar un diseño de inventario para un rodal de Pino radiata (*Pinus radiata*).
* Ejecutar dicho inventario.
* Generar una cartografía actualizada (límites y superficies).
* Determinar la productividad de sitio y condición fitosanitaria.

Antecedentes entregados a los consultores:

* Especie: *Pinus radiata*.
* Año de plantación: 2017.
* Coordenadas (EPSG:32718):UTM-X: 656163 y UTM-Y: 5600314.
* Nombre del predio: Fundo los Pinos.

# Resultados esperados



# Metodología

## Diseño de muestreo

## Información recolectada

## Procesamiento de los datos

# Equipo técnico

## Personal técnico 

Personal técnico que realizará el proyecto (indicando funciones) y
equipamiento disponible para ejecutar las labores.

# Duración

Tiempo requerido, pudiendo presentarse en la forma de carta Gantt. 

# Costos

Costos operacional y honorarios de persona